---
version: "3.9"
services:
  pyload:
    container_name: pyload
    image: lscr.io/linuxserver/pyload-ng:latest
    restart: unless-stopped
    ports:
      - 7999:8000
      #- 7227:7227 #optional
    volumes:
      - ./pyload/config:/config
      - ./pyload/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    networks:
      - download

networks:
  download:
    name: download
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/16"
          gateway: "172.18.0.1"