version: '3.9'
services:
  python3:
    container_name: python3
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes: 
      - ./code:/code
    networks:
      - python3

networks:
  python3:
    name: python3
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/16"
          gateway: "172.18.0.1"

# MEMO
#https://github.com/compose-spec/compose-spec/blob/master/build.md#build-definition
#docker build -t dev-python3 -f python3.Dockerfile