---
version: '3.9'
services:
  gvs-cli:
    container_name: gvs-cli
    build:
      context: ./cli
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./cli/images:/app/images
    networks:
      - geovisio

  gvs-api:
    container_name: gvs-api
    image: geovisio/api:latest
    build:
      context: .
      cache_from:
        - registry.gitlab.com/geovisio/api:build_cache # remote cache hosted on gitlab for faster build
    command: api
    volumes:
      - ./images/360:/data/360app
    ports:
      - 5000:5000
    depends_on:
      gvs-db:
        condition: service_healthy
    environment:
      - DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@gvs-db/${POSTGRES_DB}
    networks:
      - geovisio

  gvs-db:
    container_name: gvs-db
    image: postgis/postgis:13-3.2
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - geovisio

  gvs-website:
    container_name: gvs-website
    image: geovisio/website:latest
    ports:
      - 3001:3000
    depends_on:
      - gvs-api
    networks:
      - geovisio

networks:
  geovisio:
    name: geovisio
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/16"
          gateway: "172.18.0.1"