---
version: "3.9"
services:
  linkwarden:
    container_name: linkwarden
    image: ghcr.io/linkwarden/linkwarden:latest
    restart: always    
    ports:
      - 3000:3000
    depends_on:
      - linkwarden-db
    volumes:
      - ./data:/data/data    
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@linkwarden-db:5432/linkwarden
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      # - PAGINATION_TAKE_COUNT=${PAGINATION_TAKE_COUNT}
      # - STORAGE_FOLDER=${STORAGE_FOLDER}
      # - AUTOSCROLL_TIMEOUT=${AUTOSCROLL_TIMEOUT}
      # - NEXT_PUBLIC_DISABLE_REGISTRATION=${NEXT_PUBLIC_DISABLE_REGISTRATION}
      # - IMPORT_SIZE_LIMIT=${IMPORT_SIZE_LIMIT}
      # - SPACES_KEY=${SPACES_KEY}
      # - SPACES_SECRET=${SPACES_SECRET}
      # - SPACES_ENDPOINT=${SPACES_ENDPOINT}
      # - SPACES_REGION=${SPACES_REGION}
      # - NEXT_PUBLIC_EMAIL_PROVIDER=${NEXT_PUBLIC_EMAIL_PROVIDER}
      # - EMAIL_FROM=${EMAIL_FROM}
      # - EMAIL_SERVER=${EMAIL_SERVER}
      - TZ=Europe/Paris
    networks:
      - linkwarden

  linkwarden-db:
    container_name: linkwarden-db
    image: postgres:latest
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Europe/Paris
    networks:
      - linkwarden

networks:
  linkwarden:
    name: linkwarden
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/16"
          gateway: "172.18.0.1"